### ISSUE TITLE
Filtering, sorting and paging

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard.Gallery#1]
sort newest

**Comment by agriffard** [comment]
Ex: http://gallery.orchardproject.net/Packages/Themes
Provide a link to sort by newly created.
https://twitter.com/whjacobsen/status/730972049880059904

**Comment by whjacobsen** [comment]
A link to sort by 'most downloads' would also be nice

**Comment by agriffard** [comment]
There should be filter, sorting and paging options similar to the first gallery :
http://orchardgalleryfe.cloudapp.net/List/Search?packageType=Modules&searchCategory=All+Categories&searchTerm=author%3A+Bertrand+Le+Roy&sortOrder=package-created&pageSize=15

**Comment by agriffard** [comment]
Should be fixed. Needs to be tested and deployed on the gallery.
