### ISSUE TITLE
1.9.2 modules not available in gallery 

### ISSUE THREAD

**Issue by jdedwards3** [OrchardCMS/Orchard.Gallery#12]
The email messaging module version 1.6 is available to download from gallery. 

When I look at downloaded source code of Orchard 1.9.2 I can see the module email messaging version 1.9.2. 

This is happening for other modules as well like import export. 

Why is the gallery not showing most current version of these, among other, modules?

**Comment by rtpHarry** [comment]
I thought this was related to the semver issue (#15) but it seems that these packages don't exist on the old gallery either:
- http://orchardgalleryfe.cloudapp.net/List/Modules/Orchard.Module.Orchard.Email

I think you are just looking at old modules which used to be addons but have been folded into the core and are now discontinued as gallery modules.

**Comment by jdedwards3** [comment]
Wouldn't it make sense to remove these older versions from the gallery if they are indeed part of the core now?

**Comment by rtpHarry** [comment]
Yeah that would be tidy, I don't know if there would be any implications for clients stuck in the past though.

An update to the description to explain what's happened would probably be the cleanest option.
