### ISSUE TITLE
Set up 301 redirects for old packages to new packages

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard.Gallery#14]
Need to setup a regex that will match and forward the old package urls to the new package urls.

Looks like the old format was `https://gallery.orchardproject.net/List/Themes/Orchard.Theme.PJS.Bootstrap` which now needs to be forwarded to `https://gallery.orchardproject.net/Packages/Orchard.Theme.PJS.Bootstrap`

Also for modules `https://gallery.orchardproject.net/List/Modules/Orchard.Module.Mello.ImageGallery` should forward to `https://gallery.orchardproject.net/Packages/Orchard.Module.Mello.ImageGallery`

**Comment by sebastienros** [comment]
Done, thanks
