### ISSUE TITLE
Install Module in Orchard installs the wrong item

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard.Gallery#19]
When trying to install a module via the admin portal, the wrong item is installed.
This may have to do with the Feed filter call: 
`https://gallery.orchardproject.net/api/FeedService/Packages()?$filter=%22tolower(Id)%20eq%20%27orchard.module.contrib.googleanalytics%27%22&$orderby=Id`

The above call retrieves all packages instead of the filtered ones, and the package manager then tries to install the Classic theme, regardless of which module the user actually wanted to install.

Repro steps:
Run Orchard Dev / 1.10 branch
Go to the Module gallery
Search for `Google Analytics`
Click on `install`

What should happen:
The google analytics module should install

What actually happens:
The Classic theme gets installed.

**Comment by geertdoornbos** [comment]
It works Sebastien. Thanks.

Do you know what caused this issue? Was it [this](https://github.com/OrchardCMS/Orchard/commit/6a2b56e714e0e8078abc5830929cdcd24d0c30b1)?

**Comment by sebastienros** [comment]
The issue was that the new gallery did not expect this kind of request.

**Comment by geertdoornbos** [comment]
Yes of course, but why wasn't it expected. A change in NuGet.Core or Orchard.Packaging? [This](https://github.com/OrchardCMS/Orchard/commit/6a2b56e714e0e8078abc5830929cdcd24d0c30b1) change was almost 3 months ago (and nobody noticed?)
Something must have changed or it has never worked before. [_learning mode_]

**Comment by sebastienros** [comment]
I We released a new Gallery, with brand new code, which was incomplete.
