### ISSUE TITLE
Need Rewrite Rule for old links

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard.Gallery#24]
Gallery links to Modules and Themes have all changed so Me, Orchard Developers and Others have to go through all there past Blog Posts, Stack-overflow Twitter......where ever of postings discussions on what ever Orchard and try to fix all the dead links Referencing Orchard Modules or Themes.
Just one rewrite rule from /List/Modules/ to /Packages/ should be simple so the thousands of now broken links to Orchard can  be corrected, Looks bad please fix.
Moff.Social old and new links.
Moff.Social old link: as http://gallery.orchardproject.net/List/Modules/Orchard.Module.Moff.Social
Moff.Social new link as: http://gallery.orchardproject.net/Packages/Orchard.Module.Moff.Social

**Comment by rtpHarry** [comment]
I did attempt this in #14.

Most of the old urls forward correctly but it looks like a few slipped through the cracks. 

I'll make some further modifications.

**Comment by rtpHarry** [comment]
@sebastienros 

```
            <rule name="Redirect old module and theme urls including naked root">
                <match url="^List/((?:Modules|Themes)[/]?.*)" />
                <action type="Redirect" url="Packages/{R:1}" />
            </rule>
```

should be:

```
            <rule name="Redirect old module and theme urls including naked root">
                <match url="^List/(?:Modules|Themes)[/]?(.*)" />
                <action type="Redirect" url="Packages/{R:1}" />
            </rule>
```

Can you update it on the site please? I can't do a direct PR for it.

**Comment by rtpHarry** [comment]
@sebastienros I keep coming across 404's with links within the community. Could you implement this fix I proposed please? If you're busy just send me the web.config and I'll send you the completed one back.

**Comment by agriffard** [comment]
Let's remind it to @sebastienros during the next triage meeting.

**Comment by sebastienros** [comment]
I updated it, seems to work for me. Try with new package names in case you already have a permanent redirection to a wrong url.
