### ISSUE TITLE
Can't find the source code ?

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard.Gallery#3]
May be I misunderstood, I was believing it was here ?

**Comment by rtpHarry** [comment]
I'd like to see this too, I think I could probably tackle some of these issues.

I saw in the podcast video that this ticket has been reviewed and it is @sebastienros to add the code so you're not mistaken.

**Comment by sebastienros** [comment]
Open source is so over rated these days, I am trying a new approach.

**Comment by rtpHarry** [comment]
Nope-n source?

**Comment by CSurieux** [comment]
Good move codeless open source, very ms.

**Comment by bleroy** [comment]
You do understand that was a joke, right?

**Comment by CSurieux** [comment]
I do think so, thanks, as usual. I was also trying to 'modelize' some template of joke around the open source spirit in ms boys.

**Comment by IntranetFactory** [comment]
@sebastienros would you mind to provide some information if/when/how the source of the new gallery will be made available?

**Comment by sebastienros** [comment]
It's available now. I will also create the two other themes that are used on the public gallery, TheBootstrapMachine which is a base Bootstrap theme, and TheGalleryMachine which is the actual one used, child of the former.
