### ISSUE TITLE
How to Auto Recycle an application pool

### ISSUE THREAD

**Issue by mtcindia** [OrchardCMS/Orchard.Gallery#33]
I have developed my website uisng Orchard in mvc 3.0.and i have hosted it under iis enviroment.but i am facing application pool related issue .Is there any way to auto heal iis hosted website that i can perform recycling of app pool.

**Comment by sebastienros** [comment]
This is not the place to ask questions on Orchard. Please use the Gitter room on file an issue on the OrchardCMS repository.

I think you should look into IIS documentation for options to recycle your app automatically.
