### ISSUE TITLE
Issue with search results

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/Orchard.Gallery#5]
Just did a search for "Google Code Prettify" to find the module
https://gallery.orchardproject.net/Packages/Orchard.Module.Devworx.CodePrettify

And it does not show up in the search results, despite being a 100% match on the title.

Searching for just the term "Prettify" finally shows the Google Code Prettify as the last result.

Must say that this is less than ideal.

**Comment by agriffard** [comment]
Searching for "Google Code Prettify", I can see it on the last page : http://gallery.orchardproject.net/Packages/Modules?q=Google%20Code%20Prettify&page=7 .

**Comment by petedavis** [comment]
So are the search results listed in the reverse ranking order? A 100% name match on the last page would seem to indicate that it was.

**Comment by SzymonSel** [comment]
Currently I think the order is by oldest to newest.

-----Original Message-----

**Comment by agriffard** [comment]
Should be fixed when last commit is deployed. See #1
